#include "EntitiesMP/Projectile.h"

// Resources to be excluded from the shuffling
static const CTString _astrExclude[] = {
  "Fonts\\",
  "Textures\\Interface",
  "TexturesMP\\Interface",
};

// Random quotes
#define CT_QUOTES 75
static const CTString _astrQuotes[CT_QUOTES] = {
  "Aaaah_My_Old_Love",
  "Aaah_Its_Just_What_I_Have_Always_Wanted",
  "Am_I_The_Man_Or_Am_I_The_Man",
  "Bastards",
  "Come_On_I_Have_Enough_Lead_For_All_Of_You",
  "Come_On_Just_Try_To_Hurt_Me_Now",
  "Come_On_Play_With_Me_Now",
  "Damn",
  "Die_When_I_Kill_You",
  "Double_Your_Gun_Double_Your_Fun",
  "Finally_Some_Sci_Fi_Mumbo_Jumbo",
  "Good_Morning_Babylon",
  "Haha_Now_You_Are_All_Fired",
  "Heh_Party_Time",
  "Hey_Didnt_I_Kick_Your_Ass_Two_Rooms_Back",
  "Hey_Guys_Lets_Play_Hot_Potato",
  "Hey_Where_Are_You_Going",
  "I_Am_A_Lumberjack",
  "I_Am_Ready_For_Some_Serious_Carnage",
  "I_Hate_Crates",
  "I_Hate_Running_Backwards",
  "I_Need_A_Vacation",
  "I_smell_some_real_firepower_around_here",
  "I_Wish_My_Tv_Had_A_Stand_Like_That",
  "I_Wont_Pass_By_Lets_Fight",
  "Lets_Get_Out_Of_Here",
  "Lets_Raise_The_Rhythm",
  "Liftboy_This_Isnt_My_Floor",
  "Look_Enough_Lead_For_Everybody_Hahaha",
  "Look_Ma_I_Am_A_Lumberjack",
  "Man_Its_Cold_My_Nipples_Are_Like_Pencil_Erasers ",
  "Man_You_Are_Ugly",
  "Maybe_I_Should_Follow_The_Light",
  "Minigun_For_Maximum_Pleasure",
  "Much_better",
  "My_Flaming_Fists_Of_Fury",
  "Noooo",
  "Not_Again",
  "Now_I_Am_Seriously_Serious",
  "Now_I_Got_Your_Ticket_To_Hell",
  "Now_This_Baby_Should_Warm_Things_Up",
  "Now_This_Is_What_I_Call_A_Gun",
  "Now_You_Will_Dance_My_Tune",
  "Oh_God_Never_Underestimate_The_Power",
  "Oh_My_God_I_Killed_All_Pinkys_Brothers",
  "Oh_Yeah_Finally_Some_Dark_Dungeons",
  "Oh_Yeah_Shake_Baby_Shake",
  "Olala_I_Love_This_One",
  "Oooooo_Yeah",
  "Rocket_Ranger",
  "Rocket_Roll",
  "Say_Hello_To_Papa",
  "Serious_Speed",
  "Serious_Weaponry_For_Serious_People",
  "Seriously_Man_This_Isnt_Funny",
  "Sorry_Did_I_Wake_You",
  "That_Was_Close",
  "The_Doorman_Should_Wear_A_Suit",
  "These_Guys_Have_Seriously_Lost_Their_Heads",
  "Time_To_Inflict_Some_Serious_Pain",
  "To_be_or_not_to_be",
  "Two_Heads",
  "Ugh_Those_Babylonians_Were_Totally_Crazy",
  "Wait_For_Me_Montezuma_Here_I_Come",
  "Whadda_Hell_Is_That_Where_Is_The_Grail",
  "What_Are_You_Screaming",
  "What_Are_You_Waiting_For_A_One_Liner",
  "What_Is_This_Looks_Like_A_Boxing_Glove",
  "Whohoo_Lets_Go_Bowling",
  "Yeeehaw",
  "Yes",
  "Yoohoo",
  "You_Look_Familiar",
  "You_May_Be_Big_But_I_Am_Serious",
  "Yuuhuu_This_Is_My_Lucky_Day",
};

// Projectile types for enemies
#define CT_ENEMYPROJECTILES 32
static const ProjectileType _aeEnemyProjectiles[CT_ENEMYPROJECTILES] = {
  PRT_LASER_RAY,
  PRT_WALKER_ROCKET,
  PRT_CATMAN_FIRE,
  PRT_HEADMAN_FIRECRACKER,
  PRT_HEADMAN_ROCKETMAN,
  PRT_BONEMAN_FIRE,
  PRT_WOMAN_FIRE,
  PRT_DRAGONMAN_FIRE,
  PRT_DRAGONMAN_STRONG_FIRE,
  PRT_STONEMAN_FIRE,
  PRT_STONEMAN_BIG_FIRE,
  PRT_STONEMAN_LARGE_FIRE,
  PRT_LAVAMAN_STONE,
  PRT_ICEMAN_FIRE,
  PRT_ICEMAN_BIG_FIRE,
  PRT_ICEMAN_LARGE_FIRE,
  PRT_HUANMAN_FIRE,
  PRT_FISHMAN_FIRE,
  PRT_MANTAMAN_FIRE,
  PRT_CYBORG_LASER,
  PRT_BEAST_PROJECTILE,
  PRT_BEAST_BIG_PROJECTILE,
  PRT_DEVIL_LASER,
  PRT_DEVIL_ROCKET,
  PRT_DEVIL_GUIDED_PROJECTILE,
  PRT_GRUNT_PROJECTILE_SOL,
  PRT_GRUNT_PROJECTILE_COM,
  PRT_GUFFY_PROJECTILE,
  PRT_DEMON_FIREBALL,
  PRT_SHOOTER_WOODEN_DART,
  PRT_SHOOTER_FIREBALL,
  PRT_LARVA_PLASMA,
};

// Projectile types for players
#define CT_PROJECTILES 18
static const ProjectileType _aeProjectiles[CT_PROJECTILES] = {
  PRT_ROCKET,
  PRT_LASER_RAY,
  //PRT_CATMAN_FIRE,
  //PRT_HEADMAN_FIRECRACKER,
  //PRT_HEADMAN_ROCKETMAN,
  PRT_BONEMAN_FIRE,
  //PRT_WOMAN_FIRE,
  //PRT_DRAGONMAN_FIRE,
  PRT_DRAGONMAN_STRONG_FIRE,
  //PRT_STONEMAN_FIRE,
  PRT_STONEMAN_BIG_FIRE,
  PRT_STONEMAN_LARGE_FIRE,
  PRT_LAVAMAN_STONE,
  //PRT_ICEMAN_FIRE,
  PRT_ICEMAN_BIG_FIRE,
  PRT_ICEMAN_LARGE_FIRE,
  //PRT_HUANMAN_FIRE,
  //PRT_FISHMAN_FIRE,
  //PRT_MANTAMAN_FIRE,
  PRT_CYBORG_LASER,
  PRT_DEVIL_LASER,
  PRT_DEVIL_ROCKET,
  PRT_GRUNT_PROJECTILE_SOL,
  PRT_GRUNT_PROJECTILE_COM,
  PRT_GUFFY_PROJECTILE,
  PRT_SHOOTER_WOODEN_DART,
  PRT_SHOOTER_FIREBALL,
  PRT_LARVA_PLASMA,
};

// Throwing projectile types
#define CT_THROWABLES 8
static const ProjectileType _aeThrowables[CT_THROWABLES] = {
  PRT_GRENADE,
  PRT_HEADMAN_BOMBERMAN,
  PRT_LAVAMAN_BIG_BOMB,
  PRT_LAVAMAN_BOMB,
  PRT_CYBORG_BOMB,
  PRT_LAVA_COMET,
  PRT_LARVA_TAIL_PROJECTILE,
  PRT_AIRELEMENTAL_WIND,
};

// Plane effects
#define CT_WAVES 13
static const BasicEffectType _aeWaves[CT_WAVES] = {
  BET_ROCKET_PLANE,
  BET_GRENADE_PLANE,
  BET_EXPLOSIONSTAIN,
  BET_SHOCKWAVE,
  BET_LASERWAVE,
  BET_BLOODSTAIN,
  BET_BLOODSTAINGROW,
  BET_CANNON_PLANE,
  BET_CANNONEXPLOSIONSTAIN,
  BET_CANNONSHOCKWAVE,
  BET_GIZMOSTAIN,
  BET_BULLETSTAINWATER,
  BET_DUST_FALL,
};

// Explosion effects
#define CT_EXPLOSIONS 15
static const BasicEffectType _aeExplosions[CT_EXPLOSIONS] = {
  BET_ROCKET,
  BET_GRENADE,
  BET_BLOODSPILL,
  BET_BLOODEXPLODE,
  BET_CANNON,
  BET_TELEPORT,
  BET_BOMB,
  BET_GIZMO_SPLASH_FX,
  BET_LIGHT_CANNON,
  BET_CANNON_NOLIGHT,
  BET_EXPLOSION_DEBRIS,
  BET_EXPLOSION_SMOKE,
  BET_SUMMONERSTAREXPLOSION,
  BET_COLLECT_ENERGY,
  BET_DUST_FALL,
};

// Ground/wall hitting effects
#define CT_HITS 28
static const BasicEffectType _aeHits[CT_HITS] = {
  BET_ROCKET,
  BET_ROCKET_PLANE,
  BET_GRENADE,
  BET_GRENADE_PLANE,
  BET_EXPLOSIONSTAIN,
  BET_SHOCKWAVE,
  BET_LASERWAVE,
  BET_BLOODSTAIN,
  BET_BLOODEXPLODE,
  BET_CANNON,
  BET_CANNON_PLANE,
  BET_CANNONEXPLOSIONSTAIN,
  BET_CANNONSHOCKWAVE,
  BET_TELEPORT,
  BET_BOMB,
  BET_GIZMOSTAIN,
  BET_BULLETSTAINSTONE,
  BET_BULLETSTAINSAND,
  BET_BULLETSTAINWATER,
  BET_BULLETSTAINUNDERWATER,
  BET_BULLETSTAINREDSAND,
  BET_LIGHT_CANNON,
  BET_CANNON_NOLIGHT,
  BET_BULLETSTAINGRASS,
  BET_BULLETSTAINWOOD,
  BET_EXPLOSION_DEBRIS,
  BET_DUST_FALL,
  BET_BULLETSTAINSNOW,
};

// Various effects
#define CT_EFFECTS 38
static const BasicEffectType _aeEffects[CT_EFFECTS] = {
  BET_ROCKET,
  BET_ROCKET_PLANE,
  BET_GRENADE,
  BET_GRENADE_PLANE,
  BET_EXPLOSIONSTAIN,
  BET_SHOCKWAVE,
  BET_LASERWAVE,
  BET_BLOODSPILL,
  BET_BLOODSTAIN,
  BET_BLOODSTAINGROW,
  BET_BLOODEXPLODE,
  BET_CANNON,
  BET_CANNON_PLANE,
  BET_CANNONEXPLOSIONSTAIN,
  BET_CANNONSHOCKWAVE,
  BET_TELEPORT,
  BET_BOMB,
  BET_BULLETTRAIL,
  BET_GIZMO_SPLASH_FX,
  BET_GIZMOSTAIN,
  BET_BULLETSTAINSTONE,
  BET_BULLETSTAINSAND,
  BET_BULLETSTAINWATER,
  BET_BULLETSTAINUNDERWATER,
  BET_BULLETSTAINREDSAND,
  BET_LIGHT_CANNON,
  BET_CANNON_NOLIGHT,
  BET_BULLETSTAINGRASS,
  BET_BULLETSTAINWOOD,
  BET_BULLETSTAINGRASSNOSOUND,
  BET_BULLETSTAINWOODNOSOUND,
  BET_EXPLOSION_DEBRIS,
  BET_EXPLOSION_SMOKE,
  BET_SUMMONERSTAREXPLOSION,
  BET_COLLECT_ENERGY,
  BET_GROWING_SWIRL,
  BET_DUST_FALL,
  BET_BULLETSTAINSNOW,
};
